import React, { useState } from 'react';
import { Search, Loader2 } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
import { recipeAPI } from '@/utils/api';
import { toast } from 'sonner';
import { useLanguage } from '@/context/LanguageContext';

export const SearchBar = ({ className = '' }) => {
    const [searchQuery, setSearchQuery] = useState('');
    const [loading, setLoading] = useState(false);
    const navigate = useNavigate();
    const { language } = useLanguage();

    const handleSearch = async (e) => {
        e.preventDefault();
        const query = searchQuery.trim();
        if (!query) return;

        setLoading(true);
        try {
            // Call the backend API with language parameter
            const lang = language?.split('-')[0] || 'en';  // Extract 'en' from 'en-US'
            const res = await recipeAPI.search(query, true, lang);
            const data = res.data;

            if (data.recipe && data.recipe.slug) {
                // Show toast for AI-generated or translated recipes
                if (data.generated && data.translated) {
                    toast.success(`Recipe for "${query}" generated and translated!`);
                } else if (data.generated) {
                    toast.success(`Recipe for "${query}" generated by Sous-Chef Linguine!`);
                } else if (data.translated) {
                    toast.info(`Recipe translated to your language`);
                }
                // Navigate to the recipe page
                navigate(`/recipe/${data.recipe.slug}`);
            } else if (data.message) {
                toast.error(data.message);
            } else {
                toast.error("Recipe not found");
            }

        } catch (error) {
            console.error("Search error:", error);
            const errorMsg = error.response?.data?.detail || "Search failed. Please try again.";
            toast.error(errorMsg);
        } finally {
            setLoading(false);
        }
    };

    return (
        <form onSubmit={handleSearch} className={`flex gap-2 ${className}`} data-testid="search-form">
            <div className="relative flex-1">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-[#1E1E1E]/40" />
                <Input
                    type="text"
                    placeholder="Search authentic recipes..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-10 bg-white border-[#E5DCC3] focus:border-[#CBA55B] rounded-none h-12"
                    data-testid="search-input"
                    disabled={loading}
                />
            </div>
            <Button
                type="submit"
                className="bg-[#6A1F2E] hover:bg-[#8B2840] text-white rounded-none h-12 px-8"
                data-testid="search-button"
                disabled={loading}
            >
                {loading ? (
                    <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Searching...
                    </>
                ) : (
                    'Search'
                )}
            </Button>
        </form>
    );
};
