import React from 'react';
import { Link } from 'react-router-dom';
import { Home, ChevronRight } from 'lucide-react';

const TermsPage = () => {
    return (
        <div className="min-h-screen bg-[#FAF7F0]">
            {/* Header */}
            <section className="bg-gradient-to-b from-[#F5F2E8] to-[#FAF7F0] py-12 px-4">
                <div className="max-w-4xl mx-auto">
                    <nav className="flex items-center gap-2 text-sm text-[#1E1E1E]/60 mb-6">
                        <Link to="/" className="hover:text-[#6A1F2E] flex items-center gap-1">
                            <Home className="h-4 w-4" /> Home
                        </Link>
                        <ChevronRight className="h-4 w-4" />
                        <span className="text-[#6A1F2E] font-medium">Terms of Service</span>
                    </nav>
                    <h1 className="text-4xl sm:text-5xl font-bold text-[#1E1E1E]" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                        Terms of Service
                    </h1>
                    <p className="text-[#1E1E1E]/70 mt-4">Last updated: December 2024</p>
                </div>
            </section>

            <section className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                <div className="bg-white rounded-xl p-8 shadow-sm space-y-8">
                    
                    <section>
                        <h2 className="text-2xl font-bold text-[#6A1F2E] mb-4" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                            1. Acceptance of Terms
                        </h2>
                        <p className="text-[#1E1E1E]/80 leading-relaxed">
                            By accessing and using Sous Chef Linguine, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, please do not use our service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-[#6A1F2E] mb-4" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                            2. Description of Service
                        </h2>
                        <p className="text-[#1E1E1E]/80 leading-relaxed">
                            Sous Chef Linguine is an authentic global recipe platform that provides traditional recipes from around the world. Our service includes recipe discovery, AI-powered recipe generation, user ratings, and recipe collections.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-[#6A1F2E] mb-4" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                            3. AI-Generated Content Disclaimer
                        </h2>
                        <p className="text-[#1E1E1E]/80 leading-relaxed mb-4">
                            Some recipes on our platform may be generated by Sous-Chef Linguine AI using traditional authenticity ranking systems. While we strive for accuracy:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 text-[#1E1E1E]/80">
                            <li>AI-generated recipes are marked as such</li>
                            <li>We do not guarantee the historical accuracy of all content</li>
                            <li>Users should verify allergen information independently</li>
                            <li>Cooking results may vary based on ingredients and techniques used</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-[#6A1F2E] mb-4" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                            4. User Accounts
                        </h2>
                        <ul className="list-disc pl-6 space-y-2 text-[#1E1E1E]/80">
                            <li>You are responsible for maintaining the confidentiality of your account</li>
                            <li>You must provide accurate information when creating an account</li>
                            <li>You may not use another person's account without permission</li>
                            <li>We reserve the right to suspend accounts that violate these terms</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-[#6A1F2E] mb-4" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                            5. User Content
                        </h2>
                        <p className="text-[#1E1E1E]/80 leading-relaxed mb-4">
                            When you submit ratings, comments, or other content:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 text-[#1E1E1E]/80">
                            <li>You grant us a non-exclusive license to display that content</li>
                            <li>You are responsible for the content you submit</li>
                            <li>Content must not be offensive, illegal, or infringe on others' rights</li>
                            <li>We may remove content that violates these terms</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-[#6A1F2E] mb-4" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                            6. Intellectual Property
                        </h2>
                        <p className="text-[#1E1E1E]/80 leading-relaxed">
                            The content, organization, graphics, design, and other matters related to Sous Chef Linguine are protected under applicable copyrights and other proprietary laws. Traditional recipes may be in the public domain, but our presentation, descriptions, and AI-generated content are proprietary.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-[#6A1F2E] mb-4" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                            7. Limitation of Liability
                        </h2>
                        <p className="text-[#1E1E1E]/80 leading-relaxed">
                            Sous Chef Linguine shall not be liable for any damages resulting from the use or inability to use our service, including but not limited to damages from food preparation, allergic reactions, or incorrect recipe information.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-[#6A1F2E] mb-4" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                            8. Changes to Terms
                        </h2>
                        <p className="text-[#1E1E1E]/80 leading-relaxed">
                            We reserve the right to modify these terms at any time. Changes will be posted on this page with an updated revision date. Continued use of the service after changes constitutes acceptance of the new terms.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-[#6A1F2E] mb-4" style={{ fontFamily: 'Cormorant Garamond, serif' }}>
                            9. Contact
                        </h2>
                        <p className="text-[#1E1E1E]/80 leading-relaxed">
                            For questions about these Terms of Service, please contact us through our <Link to="/contact" className="text-[#6A1F2E] hover:underline">Contact page</Link>.
                        </p>
                    </section>

                </div>
            </section>
        </div>
    );
};

export default TermsPage;
